### ISSUE TITLE
Use filesystem watcher on the logs to find out when a build has passed

### ISSUE THREAD

**Issue by orta** [Antondomashnev/FBSnapshotsViewer#15]
Full code: [DeveloperDirWatcher.swift](https://github.com/orta/Snapshots-app/blob/master/Snapshots/DeveloperDirWatcher.swift)

In every project logs are stored in places like this: `Users/orta/Library/Developer/Xcode/DerivedData/Aerodramus-elioeeoyxfebivbqkcrplnueiqkk/Logs/Test`

So you can watch the `Users/orta/Library/Developer/Xcode/DerivedData` folder with [File System Events](https://developer.apple.com/library/content/documentation/Darwin/Conceptual/FSEvents_ProgGuide/UsingtheFSEventsFramework/UsingtheFSEventsFramework.html)

I then

* Find all of the projects with tests ( e.g. `Aerodramus-elioeeoyxfebivbqkcrplnueiqkk` ) 
* Pull out their logs, order them by date

Rinse and repeat.

**Comment by orta** [comment]
In theory you can be smarter too, if you mix it with polling the Xcode AppleScript API, you can figure out what areactive projects, then only listen to FSEvents for those app.

**Comment by Antondomashnev** [comment]
Thanks, @orta I should've thought about this way of getting failed images. This looks more powerful than what I have now because you can get also the new records of the images.

**Comment by Antondomashnev** [comment]
Thanks once again @orta, this is implemented and will be a part of new release soon.

**Comment by orta** [comment]
Tests and everything - fancy!


 --
[·/ ]       Orta Therox

w/ Artsy <http://artsy.net/>
CocoaPods <http://cocoapods.org/> / CocoaDocs <http://cocoadocs.org/>
@orta / orta.github.com
