### ISSUE TITLE
Black menubar not working too awesome

### ISSUE THREAD

**Issue by orta** [Antondomashnev/FBSnapshotsViewer#18]
This is the only way I can tell that it's running:

![screen shot 2017-05-01 at 21 10 45](https://cloud.githubusercontent.com/assets/49038/25592951/a6b0b1c8-2eb2-11e7-932a-8189b1116b21.png)

I think it's because I have black menu bar,

![screen shot 2017-05-01 at 21 11 31](https://cloud.githubusercontent.com/assets/49038/25592972/c3b6b2a4-2eb2-11e7-85e7-ddf7f562fcf4.png)

but now I have some fails I can see it 

![screen shot 2017-05-01 at 21 12 42](https://cloud.githubusercontent.com/assets/49038/25593006/ee24dc32-2eb2-11e7-863a-8e0e941ea279.png)

**Comment by Antondomashnev** [comment]
Hah, nice catch, will fix it soon

**Comment by Antondomashnev** [comment]
Fixed 🚀
