### ISSUE TITLE
Took a quick look at a re-design 

### ISSUE THREAD

**Issue by orta** [Antondomashnev/FBSnapshotsViewer#19]
Now you've got a lot of the pieces, I threw a quick design together of what it could end up looking like?

![screen shot 2017-05-01 at 21 35 57](https://cloud.githubusercontent.com/assets/49038/25593828/37af13ce-2eb6-11e7-801a-d66e8a4fd3f2.png)

[sketch file](https://cl.ly/2U3M3s101Q14)

For this fail

![screen shot 2017-05-01 at 21 37 19](https://cloud.githubusercontent.com/assets/49038/25593909/858fb9c2-2eb6-11e7-82e0-c4ff3d04f8fc.png)

Ideally I'd like to know:

- When was this build
- What was the corresponding test for the snapshot (ideally with the ability to open that file in Xcode)
- I was never a fan of diff images, so allow switching them to mouse over versions
- Be able to scrub the mouse over the before/after, as big as possible

**Comment by Antondomashnev** [comment]
Wow, look cool 👍 
I see some more things to improve as well:
* Display better test name. (For the given example I would like to see smth like: *ARAnimatedTickView inits with deselected __deselected__*);
* Open in Kaleidoscope as mentioned here #20;
* Open in Preview app. I have an idea when clicking on it - generate an image consisted of *reference* and *new version* and open it.

**Comment by Antondomashnev** [comment]
I think this issue is a good candidate to be a roadmap for the 1.0.0 release.

**Comment by Antondomashnev** [comment]
@orta the new design is coming with the next release and was merged in #44. Thanks for your proposal I used some ideas 👍 

Would love to hear your feedback 😄
<img src="https://monosnap.com/file/mYBpEuNKI2ivUGIxqcqPkBrMTo6UJc.png" width=640>

**Comment by orta** [comment]
Awesome move forward 👍
