### ISSUE TITLE
Kaleidoscope link

### ISSUE THREAD

**Issue by yas375** [Antondomashnev/FBSnapshotsViewer#20]
Thanks a lot for your work!

I'd like to suggest to add a button `Open in Kaleidoscope` somewhere in case you can detect if there is Kaleidoscope installed on this machine. Thanks in advance.

**Comment by Antondomashnev** [comment]
Hey @yas375, thanks for the feedback 👍 I think it totally makes sense I will add it as a part of small bug fixes release soon 😄

**Comment by Antondomashnev** [comment]
Sorry, @yas375, I've moved the improvement to the 0.3.0 scope, but anyway it will be available soon.

**Comment by Antondomashnev** [comment]
Hey @yas375, check out the master branch the feature is added 😄

**Comment by yas375** [comment]
@Antondomashnev thanks!
