### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by marcelofabri** [Antondomashnev/FBSnapshotsViewer#22]
I think this is pretty self-describing 😅

**Comment by Antondomashnev** [comment]
@marcelofabri  do you have any idea of what could be an icon? Maybe a bigger version of the icon in system bar?

**Comment by marcelofabri** [comment]
I think that could work 👍

**Comment by Antondomashnev** [comment]
Done @marcelofabri, you can check how it looks in the related PR 😉
