### ISSUE TITLE
Sign binary with a distribution account

### ISSUE THREAD

**Issue by marcelofabri** [Antondomashnev/FBSnapshotsViewer#23]
> “FBSnapshotsViewer-0.2.0” can’t be opened because it is from an unidentified developer.

**Comment by Antondomashnev** [comment]
Thanks, apparently I forgot about it 😄

**Comment by Antondomashnev** [comment]
@marcelofabri could you check the [0.2.1](https://github.com/Antondomashnev/FBSnapshotsViewer/releases/tag/0.2.1) it should be signed.

**Comment by marcelofabri** [comment]
It seems it worked! Thanks 👍
