### ISSUE TITLE
Auto-update

### ISSUE THREAD

**Issue by marcelofabri** [Antondomashnev/FBSnapshotsViewer#25]
The app should auto-update, probably using [Sparkle](https://sparkle-project.org) (I guess this is what everyone uses)

**Comment by Antondomashnev** [comment]
Wow, a really good idea 👍  will definitely implement it. Thanks @marcelofabri.

**Comment by Antondomashnev** [comment]
Happy to mention, that the 0.5.0 release is with Sparkle set up now 🚀

**Comment by marcelofabri** [comment]
I've tried checking for updates, but got an error:

<img width="420" alt="error" src="https://cloud.githubusercontent.com/assets/833072/26489701/c4ee3156-4208-11e7-9f32-d611167d43ec.png">

**Comment by Antondomashnev** [comment]
@marcelofabri it's fixed now in the same release. You can re-download the binary to check 😄 
And big thanks for catching it 👏

**Comment by marcelofabri** [comment]
🎉
