### ISSUE TITLE
Text In Dark Mode Is Unreadable.

### ISSUE THREAD

**Issue by joeblau** [Antondomashnev/FBSnapshotsViewer#26]
Text in dark mode is dark with black text.  Need to add some conditionals to have white text for a dark menu bar.

![screen shot 2017-05-04 at 5 00 28 pm](https://cloud.githubusercontent.com/assets/1218847/25724797/353d1c58-30eb-11e7-8142-0bbf97750d38.png)

**Comment by Antondomashnev** [comment]
Yep, I've missed it during the fix for the menu bar icon #18. thanks for catching it, I'm not a user of dark scheme 😄

**Comment by joeblau** [comment]
Hehe yeah — I feel like I'm the only one on my team that uses dark mode.

**Comment by Antondomashnev** [comment]
I've updated the UI color scheme for the dark mode, looks better for me 😄 

<img src="https://monosnap.com/file/aFOAi07S16k3dqxRFqQ1Waa3pTS0lj.png" width=600>

**Comment by joeblau** [comment]
Yeah it looks a lot better.  thanks!
