### ISSUE TITLE
Full-size diff images or overlaid reference images

### ISSUE THREAD

**Issue by KaneCheshire** [Antondomashnev/FBSnapshotsViewer#43]
It can often be quite difficult to see the diff image, so would be ace to either be able to overlay the images and slide between the two to see the difference, or some way to view the diff image at a larger size without having to ctrl zoom the whole screen.

**Comment by Antondomashnev** [comment]
Hi @KaneCheshire thanks for the proposal, soon the new design will come and it also includes a bigger diff/split view as a reference you can check #19 

In the next milestone I'm going to add a second app style - to support full size preview - you can check the idea in #27

**Comment by Antondomashnev** [comment]
@KaneCheshire here is an upcoming design changes:
<img src="https://monosnap.com/file/To1g4G1Wp1nnS8gX7y38EzfxPjtWYe.png">

I feel it becomes better and also `diff` or `split` mode has bigger images 😄

**Comment by Antondomashnev** [comment]
Closing in favor of #27 proposed redesign.
