### ISSUE TITLE
Migrate to Swift 4

### ISSUE THREAD

**Issue by Antondomashnev** [Antondomashnev/FBSnapshotsViewer#48]
It's a good opportunity to try out new API as early as possible 😄

**Comment by Antondomashnev** [comment]
Removing from the milestone as some dependencies are not ready for Swift 4.

**Comment by babbage** [comment]
No longer necessary for dependencies to be migrated to Swift 4, in order to migrate the main project and tests. Done. https://github.com/Antondomashnev/FBSnapshotsViewer/pull/79/

**Comment by babbage** [comment]
Migrated to Swift 5 in https://github.com/Antondomashnev/FBSnapshotsViewer/pull/82.
