### ISSUE TITLE
Doesn't work for Xcode-beta

### ISSUE THREAD

**Issue by BohdanOrlov** [Antondomashnev/FBSnapshotsViewer#51]
Hey!

The app fails silently, nothing happens when I have failed a test in Xcode-beta-4.

I tried specifying the path to derived data explicitly (and restarting the app for the change to take effect) but it didn't help.

I see logs in derived data:
![image](https://user-images.githubusercontent.com/6740223/28822891-002b2bbe-76b3-11e7-8e98-68cf8538fde9.png)

Log command looks like this:
`ksdiff "/Users/bohdanorlov/Projects/Project/SnapshotTests/FailureDiffs/Tests.OwnProfileInstagramFeedViewTest/reference_testInstagramFeedView_NotConnectedAndEmpty@2x.png" "/Users/bohdanorlov/Projects/Project/SnapshotTests/FailureDiffs/Tests.OwnProfileInstagramFeedViewTest/failed_testInstagramFeedView_NotConnectedAndEmpty@2x.png"`

Let me know if I can provide additional data which can help.
Thank you.

**Comment by Antondomashnev** [comment]
Thanks for the report @BohdanOrlov 👍. I think it may be related to #50. I will try to go deeper into the problem.

**Comment by Antondomashnev** [comment]
Got the bug. Seems like the Xcode 9 has different location for test's log file.
It was changed from `Logs/Test/*.log` -> `Logs/Test/Diagnostics/AnotherFolder/*.log`.

**Comment by BohdanOrlov** [comment]
Nice! I assume both folders have to be checked. Do you plan to fix this?

**Comment by Antondomashnev** [comment]
@BohdanOrlov yep, PR is ready. I'll fix another small issue and prepare a release.

**Comment by Antondomashnev** [comment]
@BohdanOrlov release [0.6.1](https://github.com/Antondomashnev/FBSnapshotsViewer/releases/tag/0.6.1) is out 🚀

**Comment by BohdanOrlov** [comment]
@Antondomashnev Works like a charm! Many thanks. 

P.S. The swap button is a great idea ;)

**Comment by Antondomashnev** [comment]
> P.S. The swap button is a great idea ;)

Thanks @orta for the original idea 😄 But keep in mind it doesn't work with Nimble-Snapshots atm #55
