### ISSUE TITLE
Update check not working?

### ISSUE THREAD

**Issue by brentleyjones** [Antondomashnev/FBSnapshotsViewer#57]
I've never had the app tell me there is an update. Currently 0.6.1 exists, but I still get this:

<img width="532" alt="update" src="https://user-images.githubusercontent.com/158658/29075704-d71ec56c-7c18-11e7-9057-f7f7b263dc5c.png">

**Comment by Antondomashnev** [comment]
Hi @brentleyjones thanks a lot for report. I will check what's going there 😄

**Comment by Antondomashnev** [comment]
@brentleyjones I've fixed the root problem and made a workaround to receive an updates prior to the version with the fix 😄

**Comment by brentleyjones** [comment]
That worked. It found an update for 0.6. Thanks!
