### ISSUE TITLE
Can't run the app

### ISSUE THREAD

**Issue by vst-ableton** [Antondomashnev/FBSnapshotsViewer#59]
Hey Anton,
This project looks really good, and I would like to try it out. It seems something is wrong and I can't make the app work. I see the same behavior for both the compiled version and the one I compile from the source. I'm running Sierra 10.12.6.

Do you have any idea what am I doing wrong? Thanks!

![snapshot-viewer](https://user-images.githubusercontent.com/30796506/29411289-75c86ec4-8354-11e7-9cf9-267cefb3d32f.gif)

**Comment by Antondomashnev** [comment]
Hi @vst-ableton, thanks for your feedback. It may be unclear from readme, but to be able to see something you need to open the app, so you see it in the status bar and then run snapshot test. After the tests are done and if you have failed tests or recorded images the icon of the FBSnapshotsViewer will become red and if you click you'll see the pop up with information.

Let me know of that helped 😄

**Comment by vst-ableton** [comment]
All clear now! Thank you ;-)
