### ISSUE TITLE
Add support for FB_REFERENCE_IMAGE_DIR

### ISSUE THREAD

**Issue by joeblau** [Antondomashnev/FBSnapshotsViewer#61]
Our projects have snapshots in a custom directory, not in the default directory.  Could you add support for checking the project's `FB_REFERENCE_IMAGE_DIR` for snapshot diffs?

**Comment by Antondomashnev** [comment]
Hey @joeblau, do you mean you have a custom `IMAGE_DIFF_DIR ` ?

**Comment by joeblau** [comment]
Yes sir.  we have a custom `FB_REFERENCE_IMAGE_DIR` and custom `IMAGE_DIFF_DIR`.

**Comment by Antondomashnev** [comment]
I'm sorry, still not cleat what is the issue 😄 Doesn't current set up work for you?

**Comment by Antondomashnev** [comment]
Hey @joeblau do you mind to provide more details so I can help faster? 😄

**Comment by joeblau** [comment]
hey, sorry for lagging on the response.  I'll explain a bit more of the details tonight.

**Comment by joeblau** [comment]
N/M, This is an issue with our setup. 

We set the `FB_REFERENCE_IMAGE_DIR` in our projects post processor macros so it doesn't get included in derived data so the snapshot app doesn't pick up conflicts.

**Comment by Antondomashnev** [comment]
Ah, cool that it's resolved 😄
