### ISSUE TITLE
Build failed: Warning Threshold Violation

### ISSUE THREAD

**Issue by bellebethcooper** [Antondomashnev/FBSnapshotsViewer#65]
Hello,

I've just downloaded the latest release as a .zip and I'm trying to run the workspace in Xcode but the build is failing with this error:

`Warning Threshold Violation: Number of warnings exceeded threshold of 1. (warning_threshold) FBSnapshotsViewer-0.8.0`

I'm using Xcode Version 9.2 (9C40b)

Please let me know if I can share any other info to help with this!

**Comment by Antondomashnev** [comment]
Hey @bellebethcooper , sorry for the late response.It should be fixed now in master.
Out of curiosity, why do you build the project and not using the app itself?

**Comment by Antondomashnev** [comment]
Hm, ok. I'll try to be more specific. But basically, you can download the app from the [last release](https://github.com/Antondomashnev/FBSnapshotsViewer/releases/tag/0.8.0). Click on `FBSnapshotsViewer-0.8.0.app.zip` link.

**Comment by bellebethcooper** [comment]
Aha. I guess I downloaded the zip for the source code from the Releases page instead. Totally my fault then, sorry for the confusion!

**Comment by dimast85** [comment]
Hello
I've this same problem. 

`Warning Threshold Violation: Number of warnings exceeded threshold of 1. (warning_threshold)`

I'm using Xcode Version 10.3, swiftlint Version 0.34.0, MacOS 10.14.6
