### ISSUE TITLE
FBSnapshotsViewer not working Xcode 10.0

### ISSUE THREAD

**Issue by DavidTomic** [Antondomashnev/FBSnapshotsViewer#74]
Hi,

Is this lib works for you in Xcode 10.0?

For me it is not working, that is, it is not detecting anything.

**Comment by sergdort** [comment]
Same here

**Comment by Antondomashnev** [comment]
Hi there, I haven't had a chance yet to update it to Xcode 10.X will try to find sometime over the weekend.

**Comment by BohdanOrlov** [comment]
+1

**Comment by Antondomashnev** [comment]
Seems to be working now.
